# 모듈 정의하기
calc.py 모듈 만들기
모듈 내에 함수 정의 - add()

# 모듈 가져오기

# 모듈 단독으로 실행

터미널에서
```
python calc.py
```
실행
```
if __name__ '__main__' :
    # 실행 내용을 넣어준다.
```

In [3]:
print('hello')

hello

In [4]:
import calc
calc.add(10,20)
# vscode 에서 ipynb 파일의 코드 셀에서 라인넘버 보는 단축키

30

In [5]:
print(calc.add(10, 20))

30

In [6]:
import calc
calc.multiply(4,4)

16

In [7]:
import calc
calc.subtract(3,1)

2

In [3]:
import calc
calc.divide(10, 5)

2.0

In [7]:
from calc import *

In [9]:
import calc as cc
cc.add(4,4)

8

In [1]:
import math
math.sqrt(4)

2.0

In [55]:
import random
random.randint(1, 10)

4

In [48]:
import datetime
datetime.datetime.now()

datetime.datetime(2026, 8, 10, 10, 46, 44, 974554)

In [50]:
import os
os.getcwd()

'c:\\study\\python-basic'

In [52]:
import sys
sys.version

'3.13.15 (tags/v3.13.15:4061bc4, Aug  5 2026, 13:05:39) [MSC v.1944 64 bit (AMD64)]'

In [1]:
import time
time.sleep(1)

# 라이브러리 가져오기
1. pip install # pip : 파이썬의 패키지 관리자, install : 다운로드한 다음 풀어준다.
2. import 라이브러리

In [3]:
import requests

In [5]:
requests.get("https://www.google.com")

# 판다스 pandas 라이브러리 사용하기
(python -m) pip install pandas

In [ ]:
#라이브러리 호출
import pandas as pd

#표로 보기 위한 원시 데이터(딕셔너리)
data = {
    '이름': ['김철수', '이영희', '박민수', '정수진', '최영호', '한미래', '윤지원'],
    '나이': [25, 28, 22, 31, 27, 24, 29],
    '점수': [85, 92, 78, 95, 88, 73, 91]
}

In [6]:
# 판다스의 데이터프레임객체 생성
df = pd.DataFrame(data)
# 상위 5개 데이터 조회
df.head()

    이름  나이  점수
0  김철수  25  85
1  이영희  28  92
2  박민수  22  78
3  정수진  31  95
4  최영호  27  88

In [11]:
pd.DataFrame(data).head()

    이름  나이  점수
0  김철수  25  85
1  이영희  28  92
2  박민수  22  78
3  정수진  31  95
4  최영호  27  88

In [18]:
# df 의 나이 속성의 평균을 구하세요
age_mean = int(df['나이'].mean())
age_mean

26

In [16]:
round(int(df['나이'].mean()))

26

In [15]:
df.describe()

              나이         점수
count   7.000000   7.000000
mean   26.571429  86.000000
std     3.101459   7.958224
min    22.000000  73.000000
25%    24.500000  81.500000
50%    27.000000  88.000000
75%    28.500000  91.500000
max    31.000000  95.000000

# 패키지

모듈의 집합 > 디렉토리(폴더)로 묶어준다

모듈을 호출하는 코드 : C:\study\python-basic\my_first_package\main.app.py
모듈은 패키지 magic_calc 에 포함 :
C:\study\python-basic\my_first_package\magic_calc\basic_ops.py
C:\study\python-basic\my_first_package\magic_calc\advanced_ops.py